import { useEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent, type PointerEvent } from "react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { DigestDiagnostics } from "./DigestDiagnostics";

const endpoint = "/api/monthly-digest";
const tabs = { eol: "고객용 종료 안내", customer: "고객용 업데이트", sales: "영업용 업데이트", script: "발표 대본", diagnostics: "분석 진단" } as const;
const artifacts = { customer_pdf: "고객용 PDF", sales_pdf: "영업용 PDF", customer_json: "고객용 JSON", sales_json: "영업용 JSON", outline: "아웃라인", speech: "발표 대본", full_json: "전체 JSON" };
type Tab = keyof typeof tabs;
type Item = Record<string, string>;
type Report = { meta: Record<"title" | "written" | "customer_intro" | "sales_intro", string>; customer: { eol_eos: Item[]; whats_new: Item[] }; sales: Item[]; script: { outline: string; speech: string }; diagnostics: Record<string, unknown> };
type Config = { enabled: boolean; slackEnabled: boolean };
const blank = (): Report => ({ meta: { title: "AWS 월간 What's New", written: new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Seoul", year: "numeric", month: "2-digit" }).format(new Date()).replace("-", "."), customer_intro: "", sales_intro: "" }, customer: { eol_eos: [], whats_new: [] }, sales: [], script: { outline: "", speech: "" }, diagnostics: {} });
const itemFields = (tab: Tab) => tab === "eol" ? { service: "서비스", target: "대상 버전", date: "일정", badge: "배지", action: "조치 내용", source_quote: "원문 근거" } : { title: "제목", date: "일정", badge: "배지", body: "내용", url: "참고 URL", source_quote: "원문 근거" };
const updateKeys = ["title", "badge", "date", "body", "url", "source_quote"];

function serialize(report: Report) { const json = JSON.stringify(report); if (new TextEncoder().encode(json).length > 1_800_000) throw new Error("전체 리포트는 1.8MB까지 저장할 수 있습니다. 내용을 나눠 주세요."); return json; }
function importReport(value: unknown): Report {
  if (!value || typeof value !== "object") throw new Error("전체 백업 JSON 파일을 선택하세요.");
  const source = value as Record<string, unknown>;
  if (!source.customer || !Array.isArray(source.sales)) throw new Error("전체 백업 JSON 파일을 선택하세요.");
  const report = blank(), text = (item: unknown, limit = 12000) => { if (item == null) return ""; if (typeof item !== "string" || item.length > limit) throw new Error("JSON의 텍스트 형식 또는 길이를 확인하세요."); return item; };
  const meta = source.meta as Record<string, unknown> | undefined;
  for (const key of Object.keys(report.meta) as (keyof Report["meta"])[]) if (meta?.[key] != null) report.meta[key] = text(meta[key]);
  const script = source.script as Record<string, unknown> | undefined;
  report.script.outline = text(script?.outline, 100000); report.script.speech = text(script?.speech, 100000);
  const rows = (input: unknown, keys: string[]) => { if (!Array.isArray(input) || input.length > 150) throw new Error("항목은 영역별 150개까지 가능합니다."); return input.map((row) => { if (!row || typeof row !== "object") throw new Error("항목 형식을 확인하세요."); const sourceRow = row as Record<string, unknown>; return Object.fromEntries(keys.map((key) => [key, text(sourceRow[key])])) as Item; }); };
  const customer = source.customer as Record<string, unknown>;
  report.customer.eol_eos = rows(customer.eol_eos ?? [], ["service", "target", "date", "badge", "action", "source_quote"]);
  report.customer.whats_new = rows(customer.whats_new ?? [], updateKeys); report.sales = rows(source.sales, updateKeys);
  report.diagnostics = source.diagnostics && typeof source.diagnostics === "object" ? source.diagnostics as Record<string, unknown> : {};
  serialize(report); return report;
}
function saveFile(content: BlobPart, name: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })), anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 10_000); }
async function request(path: string, body: unknown) { const response = await fetch(endpoint + path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || `요청에 실패했습니다. (${response.status})`); } return response; }

export function MonthlyDigest({ onDirty }: { onDirty: (dirty: boolean) => void }) {
  const [config, setConfig] = useState<Config | null>(null), [report, setReport] = useState<Report>(blank), [tab, setTab] = useState<Tab>("eol"), [files, setFiles] = useState<File[]>([]), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [progress, setProgress] = useState(0), [message, setMessage] = useState(""), [error, setError] = useState(""), [preview, setPreview] = useState(""), [previewKind, setPreviewKind] = useState<"customer" | "sales">("customer");
  const workspace = useRef<HTMLDivElement>(null);
  const [editorWidth, setEditorWidth] = useState(58);
  const reloadConfig = () => { setError(""); api<Config>(`${endpoint}/config`).then(setConfig).catch((e) => { setConfig(null); setError(e.message); }); };
  useEffect(reloadConfig, []); useEffect(() => onDirty(dirty || busy), [dirty, busy, onDirty]);
  const list = useMemo(() => tab === "eol" ? report.customer.eol_eos : tab === "customer" ? report.customer.whats_new : report.sales, [tab, report]);
  const change = (mutator: (current: Report) => Report) => { try { const next = mutator(report); serialize(next); setReport(next); setDirty(true); setPreview(""); } catch (e) { setError((e as Error).message); } };
  const updateMeta = (key: keyof Report["meta"], value: string) => change((current) => ({ ...current, meta: { ...current.meta, [key]: value } }));
  const updateItem = (index: number, key: string, value: string) => change((current) => { const next = structuredClone(current), target = tab === "eol" ? next.customer.eol_eos : tab === "customer" ? next.customer.whats_new : next.sales; target[index][key] = value; return next; });
  const run = async (task: () => Promise<void>) => { if (busy) return; setBusy(true); setError(""); setMessage("처리 중입니다…"); setProgress(0); try { await task(); } catch (e) { setError((e as Error).message); setMessage(""); } finally { setBusy(false); } };
  const chooseFiles = (next: File[]) => { if (next.length > 3 || next.some((file) => !file.name.toLowerCase().endsWith(".pdf") || file.size <= 0 || file.size > 20 * 1024 * 1024)) { setFiles([]); setError("PDF는 최대 3개, 파일당 20MB까지 선택하세요."); } else { setFiles(next); setError(""); } };
  const analyze = async () => { if (!files.length || (dirty && !confirm("분석 결과로 현재 편집 내용을 바꿀까요? 먼저 JSON 저장을 권장합니다."))) return; await run(async () => { const upload = await (await request("/upload-url", { files: files.map((file) => ({ name: file.name, size: file.size })) })).json() as { session_id: string; uploads: { key: string; url: string; fields: Record<string, string> }[] }; for (const [index, item] of upload.uploads.entries()) { const form = new FormData(); Object.entries(item.fields).forEach(([key, value]) => form.append(key, value)); form.append("file", files[index]); if (!(await fetch(item.url, { method: "POST", body: form, credentials: "omit" })).ok) throw new Error("PDF 업로드에 실패했습니다. 파일 크기와 연결 상태를 확인하세요."); } const response = await request("/analyze", { session_id: upload.session_id, keys: upload.uploads.map((item) => item.key) }); if (!response.body) throw new Error("분석 응답을 읽을 수 없습니다."); const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = "", completed = false; const consume = (line: string) => { if (!line.trim()) return; const event = JSON.parse(line) as { error?: string; success?: boolean; data?: unknown; progress?: number; msg?: string }; if (event.error) throw new Error(event.error); if (event.success) { setReport(importReport(event.data)); setDirty(true); setPreview(""); completed = true; setProgress(100); setMessage("분석을 완료했습니다. 내용을 검토한 뒤 JSON으로 저장해 주세요."); } else { setProgress(event.progress ?? 0); setMessage(event.msg ?? "분석 중입니다."); } }; try { while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value, { stream: !done }); if (buffer.length > 2_000_000) throw new Error("분석 응답이 너무 큽니다."); let end: number; while ((end = buffer.indexOf("\n")) >= 0) { consume(buffer.slice(0, end)); buffer = buffer.slice(end + 1); } if (done) { consume(buffer); break; } } if (!completed) throw new Error("분석 연결이 중간에 끊겼습니다. 완료된 결과가 없습니다."); } finally { await reader.cancel().catch(() => {}); reader.releaseLock(); } }); };
  const importFile = async (file?: File) => { if (!file || (dirty && !confirm("현재 편집 내용을 불러온 파일로 바꿀까요?"))) return; await run(async () => { if (file.size > 2_000_000) throw new Error("JSON 파일은 2MB까지 불러올 수 있습니다."); setReport(importReport(JSON.parse(await file.text()))); setDirty(true); setPreview(""); setMessage("JSON을 불러왔습니다."); }); };
  const disabled = busy || !config?.enabled;
  const startResize = (event: PointerEvent<HTMLDivElement>) => {
    const bounds = workspace.current?.getBoundingClientRect();
    if (!bounds) return;
    event.preventDefault();
    const move = (next: globalThis.PointerEvent) => setEditorWidth(Math.min(70, Math.max(38, ((next.clientX - bounds.left) / bounds.width) * 100)));
    const stop = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", stop); };
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", stop, { once: true });
  };
  const resizeWithKeyboard = (event: KeyboardEvent<HTMLDivElement>) => {
    if (!(["ArrowLeft", "ArrowRight", "Home", "End"] as string[]).includes(event.key)) return;
    event.preventDefault();
    setEditorWidth((width) => event.key === "Home" ? 38 : event.key === "End" ? 70 : Math.min(70, Math.max(38, width + (event.key === "ArrowRight" ? 2 : -2))));
  };
  return <div ref={workspace} className="digest-workspace" style={{ "--digest-editor-width": `${editorWidth}%` } as CSSProperties}>
    <section className="flex min-w-0 flex-col gap-4" aria-label="리포트 편집기">
      <header className="flex flex-wrap items-center gap-2"><div className="mr-auto"><h1 className="text-2xl font-semibold">AWS 월간 What's New</h1><p className="text-sm text-muted-foreground">PDF 분석부터 검토, 미리보기와 산출물 저장까지 한 화면에서 작업합니다.</p></div><Button variant="outline" disabled={busy} onClick={() => { try { saveFile(serialize(report), "aws-monthly-report.json", "application/json"); setDirty(false); setMessage("전체 JSON 다운로드를 요청했습니다."); } catch (e) { setError((e as Error).message); } }}>JSON 저장</Button><Button variant="outline" disabled={disabled} onClick={() => run(async () => saveFile(await (await request("/pdf", { state: report, kind: previewKind })).blob(), `${previewKind}.pdf`, "application/pdf"))}>{previewKind === "sales" ? "영업용" : "고객용"} PDF</Button><Button disabled={disabled} onClick={() => run(async () => saveFile(await (await request("/download-all", report)).blob(), "aws-monthly-report.zip", "application/zip"))}>전체 산출물 ZIP</Button></header>
      {error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{!config?.enabled && <Alert><AlertDescription>월간 What's New 연결을 준비 중입니다. JSON 불러오기와 편집은 사용할 수 있습니다. <Button variant="link" onClick={reloadConfig}>연결 다시 확인</Button></AlertDescription></Alert>}{(message || busy) && <div className="rounded-md border p-3 text-sm" role="status">{message}{busy && <progress className="ml-3 align-middle" max={100} value={progress}>{progress}%</progress>}</div>}
      <fieldset disabled={busy} className="rounded-lg border p-4"><legend className="px-1 text-sm font-medium">원본 자료</legend><div className="flex flex-wrap items-center gap-2"><Input id="digest-files" className="max-w-sm" type="file" accept="application/pdf,.pdf" multiple onChange={(e) => chooseFiles([...e.target.files!])} /><Button id="digest-analyze" disabled={disabled || !files.length} onClick={analyze}>AI 분석 시작</Button><label className="inline-flex cursor-pointer items-center rounded-md border px-3 py-2 text-sm">기존 JSON 불러오기<input id="digest-import" className="sr-only" type="file" accept="application/json,.json" onChange={(e) => importFile(e.target.files?.[0])} /></label></div><p className="mt-2 text-sm text-muted-foreground">{files.map((file) => file.name).join(" · ") || "선택된 PDF가 없습니다. 최대 3개, 파일당 20MB"}</p></fieldset>
      <fieldset disabled={busy} className="rounded-lg border p-4"><legend className="px-1 text-sm font-medium">문서 정보</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">리포트 제목<Input value={report.meta.title} onChange={(e) => updateMeta("title", e.target.value)} /></label><label className="text-sm">작성월<Input placeholder="2026.09" value={report.meta.written} onChange={(e) => updateMeta("written", e.target.value)} /></label></div></fieldset>
      <div className="flex flex-wrap gap-2" aria-label="리포트 편집 영역">{Object.entries(tabs).map(([id, name]) => <Button key={id} variant={tab === id ? "secondary" : "outline"} aria-pressed={tab === id} disabled={busy} onClick={() => setTab(id as Tab)}>{name}</Button>)}</div>
      <fieldset disabled={busy} className="flex flex-col gap-4 rounded-lg border p-4">{tab === "diagnostics" ? <DigestDiagnostics diagnostics={report.diagnostics} /> : tab === "script" ? <>{(["outline", "speech"] as const).map((key) => <label className="text-sm" key={key}>{key === "outline" ? "발표 아웃라인" : "발표 대본"}<Textarea rows={12} maxLength={100000} value={report.script[key]} onChange={(e) => change((current) => ({ ...current, script: { ...current.script, [key]: e.target.value } }))} /></label>)}</> : <DigestItems tab={tab} report={report} list={list} updateMeta={updateMeta} updateItem={updateItem} change={change} />}</fieldset>
      <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">Slack으로 산출물 공유</summary><div className="mt-3 flex flex-wrap gap-3">{Object.entries(artifacts).map(([key, label]) => <label className="text-sm" key={key}><input name="digest-artifact" type="checkbox" value={key} defaultChecked={key.endsWith("_pdf")} /> {label}</label>)}</div><Button className="mt-3" disabled={busy || !config?.slackEnabled} onClick={() => { const selected = [...document.querySelectorAll<HTMLInputElement>('[name="digest-artifact"]:checked')].map((input) => input.value); if (!selected.length) { setError("전송할 파일을 선택하세요."); return; } if (confirm(`선택한 ${selected.length}개 파일을 팀 Slack 채널에 전송할까요?`)) run(async () => { await request("/slack-notify", { state: report, selected_files: selected }); setMessage("Slack으로 전송했습니다."); }); }}>선택한 파일 Slack 전송</Button>{!config?.slackEnabled && <p className="mt-2 text-sm text-muted-foreground">Slack 전송 연결을 준비 중입니다.</p>}</details>
      <p className="text-sm text-muted-foreground">편집 내용은 자동 저장되지 않습니다. 작업을 마치기 전 JSON 저장을 이용해 주세요.</p>
    </section>
    <div className="digest-resizer" role="separator" aria-label="편집기와 미리보기 크기 조절" aria-orientation="vertical" aria-valuemin={38} aria-valuemax={70} aria-valuenow={Math.round(editorWidth)} tabIndex={0} onPointerDown={startResize} onKeyDown={resizeWithKeyboard} />
    <aside className="flex min-w-0 flex-col gap-4 rounded-lg border p-4" aria-label="리포트 미리보기"><div className="flex flex-wrap items-center gap-2"><div className="mr-auto"><strong>문서 미리보기</strong><p className="text-sm text-muted-foreground">편집 후 갱신하면 PDF와 동일한 내용을 확인할 수 있습니다.</p></div><select aria-label="미리보기 종류" className="h-9 rounded-md border bg-background px-2" value={previewKind} disabled={busy} onChange={(e) => { setPreviewKind(e.target.value as "customer" | "sales"); setPreview(""); }}><option value="customer">고객용</option><option value="sales">영업용</option></select><Button id="digest-preview" disabled={disabled} onClick={() => run(async () => { setPreview(await (await request("/preview", { state: report, kind: previewKind })).text()); setMessage("미리보기를 갱신했습니다."); })}>미리보기 갱신</Button></div><div className="min-h-96 overflow-auto rounded border bg-muted p-3">{preview ? <iframe id="digest-frame" title="리포트 미리보기" className="h-[48rem] w-full bg-white" sandbox="" referrerPolicy="no-referrer" srcDoc={preview} /> : <div className="flex min-h-80 items-center justify-center text-center text-sm text-muted-foreground">미리보기 준비<br />왼쪽에서 내용을 편집한 뒤 ‘미리보기 갱신’을 눌러 주세요.</div>}</div></aside>
  </div>;
}

function DigestItems({ tab, report, list, updateMeta, updateItem, change }: { tab: Tab; report: Report; list: Item[]; updateMeta: (key: keyof Report["meta"], value: string) => void; updateItem: (index: number, key: string, value: string) => void; change: (mutator: (current: Report) => Report) => void }) {
  const intro = tab === "sales" ? "sales_intro" : "customer_intro";
  const mutate = (fn: (target: Item[]) => void) => change((current) => { const next = structuredClone(current), target = tab === "eol" ? next.customer.eol_eos : tab === "customer" ? next.customer.whats_new : next.sales; fn(target); return next; });
  return <><label className="text-sm">이번 달 핵심 요약<Textarea rows={4} maxLength={12000} value={report.meta[intro]} onChange={(e) => updateMeta(intro, e.target.value)} /></label>{list.map((item, index) => <article className="rounded-md border p-3" key={index}><div className="mb-3 flex flex-wrap items-center gap-2"><strong>항목 {index + 1}</strong><Button size="sm" variant="outline" disabled={index === 0} onClick={() => mutate((target) => [target[index], target[index - 1]] = [target[index - 1], target[index]])}>위로</Button><Button size="sm" variant="outline" disabled={index === list.length - 1} onClick={() => mutate((target) => [target[index], target[index + 1]] = [target[index + 1], target[index]])}>아래로</Button><Button size="sm" variant="outline" onClick={() => { if (confirm("이 항목을 삭제할까요?")) mutate((target) => target.splice(index, 1)); }}>삭제</Button></div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(itemFields(tab)).map(([key, label]) => <label className={key === "body" || key === "action" ? "text-sm sm:col-span-2" : "text-sm"} key={key}>{label}{key === "body" || key === "action" ? <Textarea rows={5} maxLength={12000} data-key={key} value={item[key] ?? ""} onChange={(e) => updateItem(index, key, e.target.value)} /> : <Input maxLength={12000} data-key={key} value={item[key] ?? ""} onChange={(e) => updateItem(index, key, e.target.value)} />}</label>)}</div></article>)}{!list.length && <p className="text-sm text-muted-foreground">아직 항목이 없습니다. PDF를 분석하거나 직접 추가하세요.</p>}<Button type="button" variant="outline" disabled={list.length >= 150} onClick={() => mutate((target) => target.push({}))}>항목 추가</Button></>;
}
